### PR TITLE
[JSON] Support JSONdotNET

### PR DESCRIPTION
**Pull request by jrappen**
compare:

* <https://www.newtonsoft.com/json/help/html/DatesInJSON.htm#DatesAndJsonNET>
* <https://www.developer.com/microsoft/dealing-with-json-dates-in-asp-net-mvc/>
* <https://github.com/featurist/dotnet-json-date>

Co-authored-by: Keith Hall <keith-hall@users.noreply.github.com>
Co-authored-by: Michael B. Lyons <michaelblyons@users.noreply.github.com>

### CODE REVIEW

**Comment by jrappen** [comment]
FYI @keith-hall, I'll work on this later.

**Comment by jrappen** [comment]
* <https://www.newtonsoft.com/json/help/html/DatesInJSON.htm#DatesAndJsonNET>
* <https://www.developer.com/microsoft/dealing-with-json-dates-in-asp-net-mvc/>
* <https://github.com/featurist/dotnet-json-date>

**Comment by jrappen** [comment]
@keith-hall Follow up question: Do you expect DateTime objects to be supported on top of the datetime strings?

**Comment by keith-hall** [comment]
Hi, nope, I don't :)

**Comment by jrappen** [comment]
@keith-hall

- suggestions for `first_line_match`?
- suggestions for file extensions?
- does the regex cover all your use-cases?

**Comment by jrappen** [comment]
@michaelblyons Were you expecting further additions here to support json.NET datetime strings?

**Comment by michaelblyons** [comment]
I thought you folks were doing the first part of this but not the second part. Is that already matched in a parent file? All I see here is the ISO date, not Microsoft's janky date format.

**Comment by jrappen** [comment]
Is json.NET prior to v4.5 widely used? Keith's first link mentions the ISO date being the current standard, the janky format being outdated and the third was not required for Keith's use.

**Comment by jrappen** [comment]
I ... guess I have to add the escapes as part of the datetime stamp?

`/Date(1234)/` vs `\/Date(1234)\/`?

**Comment by jrappen** [comment]
Those backslash-escapes for the forward slashes ... is that some funky double-json-escape thing? They're not in the MSFT page Keith linked.

I don't need to cover that escaped format, do I?

**Review by michaelblyons — APPROVED** [review]

**Comment by keith-hall** [comment]
This looks good to me. I can't think of any file extensions or first line matches that would apply here. I believe it covers my use cases perfectly - thanks. Yeah I'm guessing the spurious escaped slashes are something to do with json content being output as a json string or something crazy - I unfortunately see that quite a lot ;)

**Review by keith-hall — APPROVED** [review]

**Comment by jrappen** [comment]
In that case, should I scope it as invalid with the double escape?

**Pull request merged**
